version: "3.8"
services:
  frontend:
    build:
      context: frontend/
      args:
        BASE_API_URL: "http://localhost:5000"
    container_name: web
    ports:
      - "80:80"
  backend:
    build: backend/
    container_name: api
    ports:
      - "5000:5000"
    environment:
      API_KEY: ${API_KEY}
